@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4592
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4623
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4628
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4416
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4518
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4979
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4521
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4980
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4247
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4570
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4032
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4820
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4347
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4518
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4951
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
127.0.0.1 - - [17/Dec/2023 16:07:28] "GET /peeps/all HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4854
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 400-192-103
127.0.0.1 - - [17/Dec/2023 16:07:28] "GET /peeps/all HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2023 16:07:28] "GET /users/get_new_user HTTP/1.1" 200 -
127.0.0.1 - - [17/Dec/2023 16:07:28] "[32mPOST /users/add_user HTTP/1.1[0m" 302 -
127.0.0.1 - - [17/Dec/2023 16:07:28] "[33mGET /users/peeps/all HTTP/1.1[0m" 404 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4561
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 22:39:44] "GET /peeps/all HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4163
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 22:39:45] "GET /peeps/all HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:39:45] "GET /users/get_new_user HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:39:45] "[35m[1mPOST /users/add_user HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 37, in add_user_to_db
    user_repository.add(user)
  File "/home/jonny/code/projects/tribe/lib/user_repository.py", line 29, in add
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
DETAIL:  Key (email)=(tomj@exaple.com) already exists.
127.0.0.1 - - [18/Dec/2023 22:39:45] "GET /users/add_user?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:39:45] "GET /users/add_user?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4510
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 22:46:49] "GET /peeps/all HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4461
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 22:46:50] "GET /peeps/all HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:46:50] "GET /users/get_new_user HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:46:51] "[35m[1mPOST /users/add_user HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 37, in add_user_to_db
    user_repository.add(user)
  File "/home/jonny/code/projects/tribe/lib/user_repository.py", line 29, in add
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
DETAIL:  Key (email)=(tomj@exaple.com) already exists.
127.0.0.1 - - [18/Dec/2023 22:46:51] "GET /users/add_user?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4830
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4935
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4274
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 22:50:16] "GET /peeps/all HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4449
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 22:50:17] "GET /peeps/all HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:50:17] "GET /users/get_new_user HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:50:17] "[35m[1mPOST /users/add_user HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 37, in add_user_to_db
    user_repository.add(user)
  File "/home/jonny/code/projects/tribe/lib/user_repository.py", line 29, in add
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
DETAIL:  Key (email)=(tomj@exaple.com) already exists.
127.0.0.1 - - [18/Dec/2023 22:50:17] "GET /users/add_user?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:50:17] "GET /users/add_user?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4110
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 22:56:07] "[35m[1mGET /chants/all HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 16, in show_all
    chants = chant_user_repository.all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/chant_repository.py", line 11, in all
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "chants" does not exist
LINE 1: ... AS user_id, email, password, name, username FROM chants LEF...
                                                             ^
127.0.0.1 - - [18/Dec/2023 22:56:07] "GET /chants/all?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:56:07] "GET /chants/all?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:56:07] "GET /chants/all?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4834
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 22:56:13] "[35m[1mGET /chants/all HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 16, in show_all
    chants = chant_user_repository.all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/chant_repository.py", line 11, in all
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "chants" does not exist
LINE 1: ... AS user_id, email, password, name, username FROM chants LEF...
                                                             ^
127.0.0.1 - - [18/Dec/2023 22:56:13] "GET /chants/all?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:56:13] "GET /chants/all?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 22:56:13] "GET /chants/all?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4862
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4004
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4343
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4423
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4088
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 23:16:45] "[35m[1mGET /chants/all HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 16, in show_all
    chants = chant_user_repository.all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/chant_repository.py", line 11, in all
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "chants" does not exist
LINE 1: ... AS user_id, email, password, name, username FROM chants LEF...
                                                             ^
127.0.0.1 - - [18/Dec/2023 23:16:45] "GET /chants/all?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:16:45] "GET /chants/all?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:16:46] "GET /chants/all?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4051
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 23:16:51] "[35m[1mGET /chants/all HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 16, in show_all
    chants = chant_user_repository.all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/chant_repository.py", line 11, in all
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "chants" does not exist
LINE 1: ... AS user_id, email, password, name, username FROM chants LEF...
                                                             ^
127.0.0.1 - - [18/Dec/2023 23:16:51] "GET /chants/all?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:16:51] "GET /chants/all?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:16:52] "GET /chants/all?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4963
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4803
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4278
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4429
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4504
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 23:38:12] "GET /chants/all HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4292
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 23:38:17] "GET /chants/all HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:38:18] "GET /users/get_new_user HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:38:18] "[32mPOST /users/add_user HTTP/1.1[0m" 302 -
127.0.0.1 - - [18/Dec/2023 23:38:18] "[33mGET /users/chants/all HTTP/1.1[0m" 404 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4145
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 23:41:04] "GET /chants/all HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4286
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 23:41:05] "GET /chants/all HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:41:05] "GET /users/get_new_user HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:41:06] "[35m[1mPOST /users/add_user HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 37, in add_user_to_db
    user_repository.add(user)
  File "/home/jonny/code/projects/tribe/lib/user_repository.py", line 29, in add
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
DETAIL:  Key (email)=(tomj@exaple.com) already exists.
127.0.0.1 - - [18/Dec/2023 23:41:06] "GET /users/add_user?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:41:06] "GET /users/add_user?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4207
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 23:44:10] "GET /chants/all HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4137
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [18/Dec/2023 23:44:11] "GET /chants/all HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:44:11] "GET /users/get_new_user HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:44:11] "[35m[1mPOST /users/add_user HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 37, in add_user_to_db
    user_repository.add(user)
  File "/home/jonny/code/projects/tribe/lib/user_repository.py", line 29, in add
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
DETAIL:  Key (email)=(tomj@exaple.com) already exists.
127.0.0.1 - - [18/Dec/2023 23:44:11] "GET /users/add_user?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Dec/2023 23:44:11] "GET /users/add_user?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4604
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [19/Dec/2023 10:53:47] "GET /chants/all HTTP/1.1" 200 -
@@__xproc_block_delimiter__@@
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4817
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-223-509
127.0.0.1 - - [19/Dec/2023 10:53:48] "GET /chants/all HTTP/1.1" 200 -
127.0.0.1 - - [19/Dec/2023 10:53:48] "GET /users/get_new_user HTTP/1.1" 200 -
127.0.0.1 - - [19/Dec/2023 10:53:49] "[35m[1mPOST /users/add_user HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/app.py", line 37, in add_user_to_db
    user_repository.add(user)
  File "/home/jonny/code/projects/tribe/lib/user_repository.py", line 29, in add
    rows = self._connection.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonny/code/projects/tribe/lib/database_connection.py", line 42, in execute
    cursor.execute(query, params)
  File "/home/jonny/.local/share/virtualenvs/tribe-2Kqy7JYK/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
DETAIL:  Key (email)=(tomj@exaple.com) already exists.
127.0.0.1 - - [19/Dec/2023 10:53:49] "GET /users/add_user?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Dec/2023 10:53:49] "GET /users/add_user?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
